name: Paint it black

on: push

jobs:
  black:
    name: Apply black
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install black flake8
      - name: lint
        uses: wearerequired/lint-action@v1
        with:
          black: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_fix: true
          commit_message: "fix: Ran ${linter}"

