name: Paint it black

on: push

jobs:
  black:
    name: Apply black
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: black
        uses: lgeiger/black-action@master
        args: .
      - name: Commit & push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
